from flask import Flask, render_template, request
import joblib
import numpy as np
from flask import send_file
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io


app = Flask(__name__)

# Load trained model
model = joblib.load("heart_model.pkl")


def risk_level(prob):
    if prob < 0.30:
        return "Low Risk", "Maintain healthy lifestyle."
    elif prob < 0.60:
        return "Moderate Risk", "Regular monitoring recommended."
    elif prob < 0.80:
        return "High Risk", "Consult physician and improve lifestyle."
    else:
        return "Critical Risk", "Immediate cardiology consultation required."


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/predict", methods=["POST"])
def predict():
    try:
        # Get input values
        age = float(request.form["age"])
        gender = int(request.form["gender"])
        height = float(request.form["height"])
        weight = float(request.form["weight"])
        ap_hi = float(request.form["ap_hi"])
        ap_lo = float(request.form["ap_lo"])
        cholesterol = int(request.form["cholesterol"])
        gluc = int(request.form["gluc"])
        smoke = int(request.form["smoke"])
        alco = int(request.form["alco"])
        active = int(request.form["active"])

        # =============================
        # FEATURE ENGINEERING (24 total)
        # =============================

        age_years = age
        height_m = height / 100
        BMI = weight / (height_m ** 2)
        MAP = (2 * ap_lo + ap_hi) / 3
        Pulse_Pressure = ap_hi - ap_lo

        age_group = 1 if age_years > 50 else 0
        log_BMI = np.log(BMI)
        log_MAP = np.log(MAP)

        Age_BMI = age_years * BMI
        Age_BP = age_years * ap_hi
        BMI_Chol = BMI * cholesterol
        BP_Chol = ap_hi * cholesterol

        Risk_Count = (
            (1 if cholesterol > 1 else 0) +
            (1 if gluc > 1 else 0) +
            smoke +
            alco +
            (1 if active == 0 else 0)
        )

        # IMPORTANT: Exact same order as training
        features = np.array([[ 
            age, gender, height, weight, ap_hi, ap_lo,
            cholesterol, gluc, smoke, alco, active,
            age_years, height_m, BMI, MAP, Pulse_Pressure,
            age_group, log_BMI, log_MAP,
            Age_BMI, Age_BP, BMI_Chol, BP_Chol, Risk_Count
        ]])

        # Prediction
        prob = model.predict_proba(features)[0][1]

        level, advice = risk_level(prob)

        return render_template(
            "result.html",
            probability=round(prob * 100, 2),
            level=level,
            advice=advice
        )

    except Exception as e:
        return str(e)

@app.route("/download_report", methods=["POST"])
def download_report():

    probability = request.form["probability"]
    level = request.form["level"]
    advice = request.form["advice"]

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)

    p.setFont("Helvetica", 14)
    p.drawString(100, 750, "HeartCare AI - Risk Report")

    p.setFont("Helvetica", 12)
    p.drawString(100, 720, f"Predicted Probability: {probability} %")
    p.drawString(100, 700, f"Risk Level: {level}")
    p.drawString(100, 680, f"Recommendation: {advice}")

    p.drawString(100, 640, "Generated by HeartCare AI System")
    p.drawString(100, 620, "Developer: Purushottam Jha")

    p.save()
    buffer.seek(0)

    return send_file(buffer,
                     as_attachment=True,
                     download_name="Heart_Risk_Report.pdf",
                     mimetype='application/pdf')

if __name__ == "__main__":
    app.run(debug=True)